spring:
  datasource:
    url: jdbc:h2:file:./data/h2db
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driverClassName: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2: 
    console:
      enabled: true
      path: /h2-console
